#!/bin/bash

#############################################################################
# GZ302EA Power Manager - Usage Examples
#
# This script demonstrates common use cases for gz302-power-manager.sh
#############################################################################

echo "=========================================="
echo "GZ302EA Power Manager - Usage Examples"
echo "=========================================="
echo ""

echo "1. BASIC USAGE"
echo "   Check current power status:"
echo "   $ sudo ./gz302-power-manager.sh status"
echo ""

echo "2. MANUAL POWER PROFILES"
echo "   Set performance mode (when gaming or doing heavy work):"
echo "   $ sudo ./gz302-power-manager.sh performance"
echo ""
echo "   Set balanced mode (general use):"
echo "   $ sudo ./gz302-power-manager.sh balanced"
echo ""
echo "   Set powersave mode (extend battery life):"
echo "   $ sudo ./gz302-power-manager.sh powersave"
echo ""

echo "3. AUTOMATIC POWER SWITCHING"
echo "   Enable automatic switching based on AC/battery:"
echo "   $ sudo ./gz302-power-manager.sh install"
echo ""
echo "   Once installed, the system will automatically:"
echo "   • Switch to PERFORMANCE when plugged into AC"
echo "   • Switch to POWERSAVE when unplugged (on battery)"
echo ""
echo "   Disable automatic switching:"
echo "   $ sudo ./gz302-power-manager.sh uninstall"
echo ""

echo "4. REFRESH RATE CONTROL"
echo "   Set high refresh rate (120Hz) for smooth gaming/scrolling:"
echo "   $ sudo ./gz302-power-manager.sh refresh-high"
echo ""
echo "   Set low refresh rate (60Hz) to save battery:"
echo "   $ sudo ./gz302-power-manager.sh refresh-low"
echo ""

echo "5. SMART AUTO-DETECTION"
echo "   Apply profile based on current power source:"
echo "   $ sudo ./gz302-power-manager.sh auto"
echo ""

echo "=========================================="
echo "RECOMMENDED WORKFLOW"
echo "=========================================="
echo ""
echo "For laptop users who frequently switch between AC and battery:"
echo ""
echo "1. Install automatic switching once:"
echo "   $ sudo ./gz302-power-manager.sh install"
echo ""
echo "2. The system will handle everything automatically:"
echo "   - Plugged in: High performance, fast CPU/GPU"
echo "   - On battery: Power saving, extended runtime"
echo ""
echo "3. Override when needed:"
echo "   $ sudo ./gz302-power-manager.sh balanced  # For moderate usage"
echo ""

echo "For desktop/always-plugged users:"
echo ""
echo "1. Set to performance mode once:"
echo "   $ sudo ./gz302-power-manager.sh performance"
echo ""
echo "2. Set high refresh rate for best experience:"
echo "   $ sudo ./gz302-power-manager.sh refresh-high"
echo ""

echo "=========================================="
echo "WHAT EACH PROFILE DOES"
echo "=========================================="
echo ""
echo "PERFORMANCE PROFILE:"
echo "  ✓ CPU Governor: performance"
echo "  ✓ CPU Boost: enabled"
echo "  ✓ GPU Power: high"
echo "  ✓ ASUS Profile: Performance"
echo "  ✓ Best for: Gaming, rendering, compilation"
echo ""

echo "BALANCED PROFILE:"
echo "  ✓ CPU Governor: schedutil (adaptive)"
echo "  ✓ CPU Boost: enabled"
echo "  ✓ GPU Power: auto"
echo "  ✓ ASUS Profile: Balanced"
echo "  ✓ Best for: General use, web browsing, office work"
echo ""

echo "POWERSAVE PROFILE:"
echo "  ✓ CPU Governor: powersave"
echo "  ✓ CPU Boost: disabled"
echo "  ✓ GPU Power: low"
echo "  ✓ ASUS Profile: Quiet"
echo "  ✓ Best for: Battery life, light tasks"
echo ""

echo "=========================================="
echo "For more information, run:"
echo "  $ sudo ./gz302-power-manager.sh --help"
echo "=========================================="
